maps/zm_dust_world.res
maps/zm_dust_world.txt
models/zm_dust_world/25_6a6o4ka-napxaet.mdl
models/zm_dust_world/bush.mdl
models/zm_dust_world/fan_ceiling-attach.mdl
models/zm_dust_world/re_deadguy_1.mdl
models/zm_dust_world/re_deadguy_2.mdl
models/zm_dust_world/re_deadguy_3.mdl
models/zm_dust_world/tuscan_grass1a.mdl
models/zm_dust_world/TV_plasma.mdl
models/zm_dust_world/Vending_machine.mdl